"""added user role and card tables

Revision ID: 3c40ae320f10
Revises: 
Create Date: 2020-02-17 12:16:10.864722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c40ae320f10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilitycard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('initiative', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('toptext', sa.Text(), nullable=True),
    sa.Column('toploss', sa.Boolean(), nullable=True),
    sa.Column('topduration', sa.Text(), nullable=True),
    sa.Column('topaoe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topquest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bottomtext', sa.Text(), nullable=True),
    sa.Column('bottomloss', sa.Boolean(), nullable=True),
    sa.Column('bottomduration', sa.Text(), nullable=True),
    sa.Column('bottomaoe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bottomquest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('user_role_secondary',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_secondary')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('abilitycard')
    # ### end Alembic commands ###
